// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AttachDatabase(arg1:main.AttachOptions):Promise<void>;

export function AutoConnectAll():Promise<Array<main.AutoConnectResult>>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ConnectSaved(arg1:string):Promise<string>;

export function CopyTableToParquet(arg1:string):Promise<string>;

export function CreateView(arg1:string,arg2:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteTableData(arg1:string):Promise<void>;

export function DetachDatabase(arg1:string):Promise<void>;

export function DisconnectSaved(arg1:string):Promise<void>;

export function DropView(arg1:string):Promise<void>;

export function Exec(arg1:string):Promise<void>;

export function GetAISettings():Promise<main.AISettings>;

export function GetAppSettings():Promise<main.AppSettings>;

export function GetAppVersion():Promise<string>;

export function GetDatabaseSchemas(arg1:string):Promise<Array<main.SchemaInfo>>;

export function GetMCPPort():Promise<number>;

export function GetSchemaTables(arg1:string,arg2:string):Promise<Array<main.TableInfo>>;

export function GetTableColumns(arg1:string,arg2:string,arg3:string):Promise<Array<main.ColumnMeta>>;

export function GetTableDataPath(arg1:string):Promise<string>;

export function GetTableInfo(arg1:string):Promise<Array<main.ColumnInfo>>;

export function ImportFileFromBase64(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ImportFromPath(arg1:string,arg2:string):Promise<void>;

export function ImportFromUrl(arg1:string,arg2:string):Promise<void>;

export function ImportSqliteFromBase64(arg1:string,arg2:string):Promise<Array<string>>;

export function ImportSqliteFromPath(arg1:string,arg2:string):Promise<Array<string>>;

export function ListAttachedDatabases():Promise<main.QueryResult>;

export function ListConnections():Promise<Array<main.ConnectionRecord>>;

export function ListSampleDatasets():Promise<Array<main.SampleDataset>>;

export function LoadCanvasState():Promise<string>;

export function LoadExtension(arg1:string):Promise<void>;

export function LoadSampleDataset(arg1:string):Promise<Array<main.CanvasAction>>;

export function OpenFileDialog():Promise<string>;

export function OpenMultipleFilesDialog():Promise<Array<string>>;

export function Query(arg1:string):Promise<main.QueryResult>;

export function SaveAISettings(arg1:main.AISettings):Promise<void>;

export function SaveAppSettings(arg1:main.AppSettings):Promise<void>;

export function SaveCanvasState(arg1:string):Promise<void>;

export function SaveConnection(arg1:main.ConnectionRecord):Promise<main.ConnectionRecord>;

export function SaveTableData(arg1:string):Promise<void>;

export function SendAIMessage(arg1:Array<main.AIChatMessage>):Promise<main.AIResponse>;
