// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttachDatabase(arg1) {
  return window['go']['main']['App']['AttachDatabase'](arg1);
}

export function AutoConnectAll() {
  return window['go']['main']['App']['AutoConnectAll']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ConnectSaved(arg1) {
  return window['go']['main']['App']['ConnectSaved'](arg1);
}

export function CopyTableToParquet(arg1) {
  return window['go']['main']['App']['CopyTableToParquet'](arg1);
}

export function CreateView(arg1, arg2) {
  return window['go']['main']['App']['CreateView'](arg1, arg2);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteTableData(arg1) {
  return window['go']['main']['App']['DeleteTableData'](arg1);
}

export function DetachDatabase(arg1) {
  return window['go']['main']['App']['DetachDatabase'](arg1);
}

export function DisconnectSaved(arg1) {
  return window['go']['main']['App']['DisconnectSaved'](arg1);
}

export function DropView(arg1) {
  return window['go']['main']['App']['DropView'](arg1);
}

export function Exec(arg1) {
  return window['go']['main']['App']['Exec'](arg1);
}

export function GetAISettings() {
  return window['go']['main']['App']['GetAISettings']();
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetDatabaseSchemas(arg1) {
  return window['go']['main']['App']['GetDatabaseSchemas'](arg1);
}

export function GetMCPPort() {
  return window['go']['main']['App']['GetMCPPort']();
}

export function GetSchemaTables(arg1, arg2) {
  return window['go']['main']['App']['GetSchemaTables'](arg1, arg2);
}

export function GetTableColumns(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableColumns'](arg1, arg2, arg3);
}

export function GetTableDataPath(arg1) {
  return window['go']['main']['App']['GetTableDataPath'](arg1);
}

export function GetTableInfo(arg1) {
  return window['go']['main']['App']['GetTableInfo'](arg1);
}

export function ImportFileFromBase64(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportFileFromBase64'](arg1, arg2, arg3);
}

export function ImportFromPath(arg1, arg2) {
  return window['go']['main']['App']['ImportFromPath'](arg1, arg2);
}

export function ImportFromUrl(arg1, arg2) {
  return window['go']['main']['App']['ImportFromUrl'](arg1, arg2);
}

export function ImportSqliteFromBase64(arg1, arg2) {
  return window['go']['main']['App']['ImportSqliteFromBase64'](arg1, arg2);
}

export function ImportSqliteFromPath(arg1, arg2) {
  return window['go']['main']['App']['ImportSqliteFromPath'](arg1, arg2);
}

export function ListAttachedDatabases() {
  return window['go']['main']['App']['ListAttachedDatabases']();
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListSampleDatasets() {
  return window['go']['main']['App']['ListSampleDatasets']();
}

export function LoadCanvasState() {
  return window['go']['main']['App']['LoadCanvasState']();
}

export function LoadExtension(arg1) {
  return window['go']['main']['App']['LoadExtension'](arg1);
}

export function LoadSampleDataset(arg1) {
  return window['go']['main']['App']['LoadSampleDataset'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenMultipleFilesDialog() {
  return window['go']['main']['App']['OpenMultipleFilesDialog']();
}

export function Query(arg1) {
  return window['go']['main']['App']['Query'](arg1);
}

export function SaveAISettings(arg1) {
  return window['go']['main']['App']['SaveAISettings'](arg1);
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['App']['SaveAppSettings'](arg1);
}

export function SaveCanvasState(arg1) {
  return window['go']['main']['App']['SaveCanvasState'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveTableData(arg1) {
  return window['go']['main']['App']['SaveTableData'](arg1);
}

export function SendAIMessage(arg1) {
  return window['go']['main']['App']['SendAIMessage'](arg1);
}
