export const DUCKDB_FUNCTIONS = [
  // Aggregates
  'avg', 'count', 'sum', 'min', 'max', 'median', 'mode', 'stddev', 'variance',
  'first', 'last', 'list', 'list_agg', 'string_agg', 'group_concat',
  'approx_count_distinct', 'approx_quantile',
  'percentile_cont', 'percentile_disc', 'quantile_cont', 'quantile_disc',
  'regr_slope', 'regr_intercept', 'regr_r2', 'corr', 'covar_pop', 'covar_samp',
  'bit_and', 'bit_or', 'bit_xor', 'bool_and', 'bool_or',
  'histogram', 'entropy', 'kurtosis', 'skewness',
  // Window
  'row_number', 'rank', 'dense_rank', 'percent_rank', 'cume_dist',
  'ntile', 'lag', 'lead', 'first_value', 'last_value', 'nth_value',
  // String
  'concat', 'concat_ws', 'length', 'len', 'lower', 'upper', 'ltrim', 'rtrim', 'trim',
  'lpad', 'rpad', 'repeat', 'reverse', 'substr', 'substring',
  'left', 'right', 'starts_with', 'ends_with', 'contains',
  'replace', 'regexp_replace', 'regexp_matches', 'regexp_extract', 'regexp_extract_all',
  'split', 'split_part', 'string_split', 'string_split_regex',
  'instr', 'position', 'ascii', 'chr', 'unicode',
  'format', 'printf', 'format_bytes',
  'md5', 'sha256', 'base64', 'from_base64',
  'str_split', 'str_split_regex',
  'ucase', 'lcase', 'initcap', 'jaccard', 'jaro_similarity', 'jaro_winkler_similarity',
  'levenshtein', 'hamming', 'mismatches',
  'like_escape', 'not_like_escape',
  'to_hex', 'from_hex',
  // Date / Time
  'now', 'today', 'current_date', 'current_time', 'current_timestamp',
  'date_part', 'date_trunc', 'date_diff', 'date_add', 'date_sub',
  'datediff', 'dateadd', 'datesub',
  'age', 'epoch', 'epoch_ms',
  'strftime', 'strptime', 'make_date', 'make_time', 'make_timestamp', 'make_timestamptz',
  'year', 'month', 'day', 'hour', 'minute', 'second', 'microsecond', 'millisecond',
  'decade', 'century', 'millennium', 'quarter', 'week', 'weekday', 'weekofyear',
  'dayofmonth', 'dayofweek', 'dayofyear', 'isodow', 'isoyear',
  'last_day', 'monthname', 'dayname',
  'timezone', 'timezone_hour', 'timezone_minute',
  'to_timestamp', 'to_date',
  'greatest', 'least',
  // Math
  'abs', 'ceil', 'ceiling', 'floor', 'round', 'trunc', 'truncate',
  'sqrt', 'cbrt', 'exp', 'ln', 'log', 'log2', 'log10',
  'pow', 'power', 'factorial', 'gcd', 'lcm',
  'sin', 'cos', 'tan', 'asin', 'acos', 'atan', 'atan2',
  'degrees', 'radians', 'pi',
  'sign', 'signum', 'isnan', 'isinf', 'isfinite',
  'random', 'setseed',
  'bit_count', 'bit_length',
  'nextafter', 'nextdown', 'nextup',
  // List / Array
  'list_aggregate', 'list_apply', 'list_transform',
  'list_contains', 'list_has', 'list_position', 'list_indexof',
  'list_count', 'list_distinct', 'list_unique',
  'list_filter', 'list_select',
  'list_concat', 'list_append', 'list_prepend',
  'list_pop_back', 'list_pop_front', 'list_slice',
  'list_intersect', 'list_union', 'list_except',
  'list_reverse', 'list_sort', 'list_grade_up', 'list_grade_down',
  'list_sum', 'list_avg', 'list_min', 'list_max',
  'list_string_agg', 'list_extract', 'list_element',
  'list_pack', 'array_agg', 'generate_series', 'range',
  'flatten', 'unnest',
  // Struct / Map / JSON
  'struct_pack', 'struct_extract', 'struct_insert',
  'map', 'map_extract', 'map_entries', 'map_keys', 'map_values', 'map_from_entries',
  'row', 'column', 'columns',
  'json', 'json_object', 'json_array', 'json_extract', 'json_extract_string',
  'json_array_length', 'json_contains', 'json_keys', 'json_type',
  'json_serialize_sql', 'json_deserialize_sql',
  'to_json', 'json_transform', 'json_transform_strict',
  // Type conversion
  'cast', 'try_cast',
  'typeof', 'type',
  'ifnull', 'coalesce', 'nullif', 'iif', 'iff',
  'if', 'case',
  'decode', 'encode',
  // Utility
  'hash', 'range', 'generate_subscripts',
  'current_catalog', 'current_schema', 'current_user',
  'version', 'duckdb_version',
  'error', 'current_setting',
  // Table functions (used in FROM)
  'read_csv', 'read_csv_auto', 'read_parquet', 'read_json', 'read_json_auto',
  'read_ndjson', 'read_ndjson_auto',
  'parquet_schema', 'parquet_metadata', 'parquet_file_metadata',
  'glob', 'duckdb_functions', 'duckdb_tables', 'duckdb_columns', 'duckdb_schemas',
]
